### PR TITLE
Make web app standalone and use double click instead of single click to navigate

### LINKED ISSUE #20: Use double-click on classes to navigate to page about clicked class
In the dynamic web export, we currently navigate to the selected classes page on _single-click_. This is inconvenient, as users may accidently click on a class, when navigating through the diagram with click+drag. Also, it interferes with being able to move classes around.

I suggest to navigate on double-click instead.

### PR DESCRIPTION
**Pull request by edgarmueller**
* Fixes #20; this change probably has an effect on issues #21 & #22, we should check
* Make app work without the need run a web-server
To build it, follow the README instructions, then change directory to `packages/docu-app` and run `npm run build`. After that the `packages/docu-app/build` directory is self-contained, meaning that opening `index.html` should work without requiring a webserver to be started.

### CODE REVIEW

**Comment by edgarmueller** [comment]
Yes, ideally the client should have npm installed. Also, the dependencies of the React app have to be installed once in order to execute `npm run build`. Whenever the build command has finished, you can just copy the `packages/docu-app/build` folder, as you already suggest.

**Comment by planger** [comment]
Ok, thanks for the feedback!

But why does the client need to have npm installed then? Couldn't we just make sure that, when building icat, we run npm and move the `packages/docu-app/build` into a location in the icat plug-in that can then be accessed by the EntryPoint so that it just copies everything into the user-selected target location and replaces the json files?

If that would work, I think this would be the best option. This way the client doesn't need to have anything installed and only the build infrastructure has to invoke npm, if even necessary (only if the dynamic web app src folders hav been changed). Do you agree? Thanks!

**Comment by edgarmueller** [comment]
Ah, now I get what you are heading for. Yes, that should  work as well.

**Comment by planger** [comment]
Awesome, works nicely! I'll file a few follow-up bugs.

**Pull request merged**
