### PR TITLE
Updated App to handle multiple packages

### PR DESCRIPTION
**Pull request by eneufeld**
* updated libraries
* updated App code
* updated Export code

### CODE REVIEW

**Comment by eneufeld** [comment]
where do you have compile errors?

**Comment by planger** [comment]
```
Description	Resource	Path	Location	Type
Collectors cannot be resolved	EntryPoint.java	/com.eclipsesource.icat.dynamicdocu/src/com/eclipsesource/icat/dynamicdocu	line 67	Java Problem
Map cannot be resolved to a type	EntryPoint.java	/com.eclipsesource.icat.dynamicdocu/src/com/eclipsesource/icat/dynamicdocu	line 46	Java Problem
Map cannot be resolved to a type	EntryPoint.java	/com.eclipsesource.icat.dynamicdocu/src/com/eclipsesource/icat/dynamicdocu	line 70	Java Problem
Map cannot be resolved to a type	EntryPoint.java	/com.eclipsesource.icat.dynamicdocu/src/com/eclipsesource/icat/dynamicdocu	line 72	Java Problem
The method copyArtifacts(EPackage[], Map<String,SModelRoot>, Path) in the type DocuWebApp is not applicable for the arguments (EPackage[], SModelRoot, Path)	GenerateWebDocuHandler.java	/com.eclipsesource.icat.webdocu.ui/src/com/eclipsesource/icat/webdocu/ui	line 45	Java Problem
The method loadGraph(ResourceSet, URI) from the type EntryPoint refers to the missing type Map	EntryPoint.java	/com.eclipsesource.icat.dynamicdocu/src/com/eclipsesource/icat/dynamicdocu	line 46	Java Problem
The method loadGraph(ResourceSet, URI) from the type EntryPoint refers to the missing type Map	GenerateWebDocuHandler.java	/com.eclipsesource.icat.webdocu.ui/src/com/eclipsesource/icat/webdocu/ui	line 42	Java Problem
```

**Comment by planger** [comment]
Sorry, I get the following exception when trying to export `asig` from the built product:
```
!ENTRY org.eclipse.ui 4 0 2019-01-24 11:20:00.559
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/emf/ecore/resource/ResourceSet
	at com.eclipsesource.icat.dynamicdocu.EntryPoint.loadGraph(EntryPoint.java:73)
	at com.eclipsesource.icat.webdocu.ui.GenerateWebDocuHandler.execute(GenerateWebDocuHandler.java:43)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.ecore.resource.ResourceSet cannot be found by com.eclipsesource.icat.sprotty_0.0.1.20190124-1015
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
```

**Comment by eneufeld** [comment]
updated the manifest
but the exported app is not working yet as I didn't update the bundled app

**Comment by planger** [comment]
> but the exported app is not working yet as I didn't update the bundled app

Ok, thanks! Can you please do that? Then I test everything at once in the built app. Thanks a lot!

**Pull request merged**
